### ISSUE TITLE
リンク先URLが相対パスになっている

### ISSUE THREAD

**Issue by kikd** [wataruoguchi/covid19_nagano_scraper#2]
「新型コロナウイルスについて」の新着情報へのリンクが相対パスになっていました。
https://github.com/wataruoguchi/covid19_nagano_scraper/blob/183f94beedb8ec80b48c990406c60927e16fdd56/src/.json/news.json#L5

covid19の方でURLを付け足すか、スクレイピングするときに絶対パスにする必要がありそうです。
(既知でしたらすみません・・・)

**Comment by wataruoguchi** [comment]
@kikd 発見していただき、しかもissue作成してくださりありがとうございます！データ最新にしたので、次にビルドするときには反映されます。
（build hook、もう少し時間をいただくかもしれません）
