### ISSUE TITLE
お知らせの取得に失敗している

### ISSUE THREAD

**Issue by kikd** [wataruoguchi/covid19_nagano_scraper#4]
[長野県のサイト](https://www.pref.nagano.lg.jp/hoken-shippei/kenko/kenko/kansensho/joho/corona.html)のデザインに修正が入り、その影響でお知らせの取得に失敗しているようです。

![image](https://user-images.githubusercontent.com/5682821/80445441-3ef6ba00-894f-11ea-8fe4-70e0e57196ba.png)

1つのお知らせに複数のリンクがあるものもあります。
これについてはアプリ側も検討が必要かもしれません。

**Comment by kikd** [comment]
修正後のelementはこんな感じになっています。
![image](https://user-images.githubusercontent.com/5682821/80446523-086e6e80-8952-11ea-971b-f6da4527b48c.png)

**Comment by wataruoguchi** [comment]
@kikd おぉう、、文言だけの変更かと思ったんですけど、、報告ありがとうございます！

**Comment by wataruoguchi** [comment]
@kikd 対応しました！

複数リンクの方はアプリの方の表現方法を変える必要がありますね。このパターンがどの頻度で発生するのがあるかわからないので、今のところは様子見でいいかと思います。
見た目が絶対ダサくなる、工数、重要性、を考えると、個人的には優先度は低い、と思ってますが、特に強い意見もありません。

**Comment by wataruoguchi** [comment]
@kikd 一応、生HTMLを入れたJSONも作ってみました。
(src/.json/newsHtml.json)[https://github.com/wataruoguchi/covid19_nagano_scraper/blob/master/src/.json/newsHtml.json]
`href`が絶対パスだったり相対パスだったり、`target="_blank"` も無かったり、と、このままでは使えなさそうですが、参考にはなるかもしれません。

**Comment by kikd** [comment]
対応ありがとうございます！

リンクごとにアイコンがついたりするの不格好に感じます。
このパターンが頻繁に出ないとは思っているので、複数リンクの件はひとまず様子見します。
生HTMLも参考にさせていただきます。
