### ISSUE TITLE
日付とお知らせの内容が重複する

### ISSUE THREAD

**Issue by kikd** [wataruoguchi/covid19_nagano_scraper#5]
日付のないお知らせがある場合、日付とお知らせの内容が重複してしまうようです。
![image](https://user-images.githubusercontent.com/5682821/82173654-f7899b00-9908-11ea-804b-15292ca80b93.png)

![image](https://user-images.githubusercontent.com/5682821/82173788-71ba1f80-9909-11ea-847c-55bf3fdffc70.png)

確認いただけると助かります。
(レアケースだとは思いますが…)

**Comment by wataruoguchi** [comment]
@kikd wow... ありがとうございます！みてみますね！

**Comment by wataruoguchi** [comment]
空文字 "" での対応としました。issueありがとうございました！

<img width="1163" alt="Screen Shot 2020-05-19 at 7 02 02 PM" src="https://user-images.githubusercontent.com/8963743/82396646-3ef45200-9a03-11ea-9bad-b68389d54a95.png">
