### ISSUE TITLE
日付に追加する年が2020のままになっている

### ISSUE THREAD

**Issue by kikd** [wataruoguchi/covid19_nagano_scraper#9]
お知らせの日付に年を付け足す箇所が2020固定になっており、2021年以降のお知らせにも関わらず2020/mm/dd のままになっています。
https://github.com/wataruoguchi/covid19_nagano_scraper/blob/2f0db68e612b7ab07abdb50474656fbeedbb942d/src/lib/mapper.ts#L25-L26
(残念ながらここの修正をする必要が出てきてしまい、かつこの災害はもう少し長引きそうです…)

**Comment by wataruoguchi** [comment]
@kikd GitHub notification多すぎて埋もれてました。。PRありがとうございます
